apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.projectcalico.org_bgpconfigurations.yaml
  - crd.projectcalico.org_bgppeers.yaml
  - crd.projectcalico.org_blockaffinities.yaml
  - crd.projectcalico.org_caliconodestatuses.yaml
  - crd.projectcalico.org_clusterinformations.yaml
  - crd.projectcalico.org_felixconfigurations.yaml
  - crd.projectcalico.org_globalnetworkpolicies.yaml
  - crd.projectcalico.org_globalnetworksets.yaml
  - crd.projectcalico.org_hostendpoints.yaml
  - crd.projectcalico.org_ipamblocks.yaml
  - crd.projectcalico.org_ipamconfigs.yaml
  - crd.projectcalico.org_ipamhandles.yaml
  - crd.projectcalico.org_ippools.yaml
  - crd.projectcalico.org_ipreservations.yaml
  - crd.projectcalico.org_kubecontrollersconfigurations.yaml
  - crd.projectcalico.org_networkpolicies.yaml
  - crd.projectcalico.org_networksets.yaml
